MOSIP-36024
mosip/resident-ui pull request #767
Opened 2024-09-25 10:52 UTC by jayesh12234

2024-09-25 13:40 UTC, mohanachandran-s requested changes

2024-09-25 13:40 UTC, mohanachandran-s commented on uitest-resident/pom.xml
> +				<version>1.2.1-java21-SNAPSHOT</version>
make this to 1.2.1-SNAPSHOT

2024-09-26 03:29 UTC, mohanachandran-s approved these changes

2024-09-26 04:36 UTC, aranaravi approved these changes

2024-09-26 04:43 UTC, merged